---
window:
  dimensions:
    columns: 120
    lines: 50

  decorations: full

font:
  normal:
    family: "Hack Nerd Font"
    style: Regular

  size: 12.0

  offset:
    x: 0
    y: 0

dynamic_title: true

import:
  - ~/.config/alacritty/supernova.yml
  # - ~/.config/alacritty/supernova-dark.yml
  - ~/.config/alacritty/supernova-light.yml
