---
window:
  opacity: 1
  theme_variant: dark

colors:
  normal:
    black:   '#636c77'
    red:     '#ff1447'
    green:   '#4e9c00'
    yellow:  '#ba9c00'
    blue:    '#009bba'
    magenta: '#a42eff'
    cyan:    '#0ba394'
    white:   '#c9d1d7'

  bright:
    black:   '#6c7986'
    red:     '#db0025'
    green:   '#308000'
    yellow:  '#cc6800'
    blue:    '#007ea8'
    magenta: '#c557ff'
    cyan:    '#008276'
    white:   '#ffffff'
