#!/bin/sh

# Use Wayland
export QT_QPA_PLATFORM="wayland;xcb"
export QT_QPA_PLATFORMTHEME="qt6ct"
export CLUTTER_BACKEND=wayland
export WAYLAND_DISPLAY=wayland-0

# Use X
# export GDK_BACKEND=x11
# export SDL_VIDEODRIVER=x11
# export KITTY_DISABLE_WAYLAND=1
# alias alacritty="WAYLAND_DISPLAY= alacritty"
