#!/bin/sh

# Default apps
alias reload='source ~/.profile'
# shellcheck disable=SC2139
alias b="$BROWSER"
# shellcheck disable=SC2139
alias e="$EDITOR"
# shellcheck disable=SC2139
alias v="$VISUAL"
alias q='exit'

# open any file with it's default app and supress stdout
_xdg_open_silent() {
  xdg-open "$@" 2>/dev/null
}

alias x=_xdg_open_silent

# Colorized output and alternatives
# check: https://wiki.archlinux.org/index.php/Color_output_in_console 

# alias ls='ls --color=auto'
# alias ls='exa --long --git' # exa is close but not fully compliant with ls
alias ls='exa --long'
alias grep='grep --colour=auto'
alias egrep='egrep --colour=auto'
alias fgrep='fgrep --colour=auto'
alias diff='colordiff'
alias cat='bat'
alias ps='grc ps'
alias ip='ip -c'

# File management
alias rm='trash -v' # move to trash dir
alias mv='mv -v -n' # verbose and no clobber (don't overwrite)
alias cp='cp -v -n'

# Archiving
alias cf="compress"
alias xf="extract"

# compress and encrypt w/ multi-OS support
encrypt() {
  7z a -t7z -m0=lzma2 -mx=9 -mfb=64 -md=32m -ms=on -mhe=on -p "$1".7z "$1"
}

# Organization tools
alias j='journal'
alias t='timew'
