#!/bin/env zsh
# Default profile for POSIX compliant shells

alias reload='source ~/.profile'

# Preferred apps
export EDITOR="nvim"
export SUDO_EDITOR="nvim -d"
export VISUAL="alacritty -e 'nvim'"
export MANPAGER="sh -c 'col -bx | bat -l man -p'" MANROFFOPT="-c"
export BROWSER="brave"

# shellcheck disable=SC2139
alias b="$BROWSER"
# shellcheck disable=SC2139
alias e="$EDITOR"
alias q='exit'

# XDG
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_BIN_HOME="$HOME/.local/bin"

# XDG user dirs
export XDG_TEMPLATES_DIR="$HOME/.templates"
export XDG_DOWNLOAD_DIR="$HOME/Down"
export XDG_PICTURES_DIR="$HOME/Pics"
export XDG_BOOKS_DIR="$HOME/Public/fun/read/Books"
export XDG_MUSIC_DIR="$HOME/Public/fun/listen/Music"
export XDG_VIDEOS_DIR="$HOME/Public/fun/watch/Videos"

# extra dirs
export DOTFILES_HOME="$HOME/.dotfiles"

# SSH
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/gcr/ssh"

# History
export HISTFILE="$XDG_DATA_HOME/shell/history"
export HISTSIZE=1000000
export SAVEHIST=1000000

# Path
PATH="/bin:/usr/bin/:/usr/local/bin"
PATH="$PATH:$XDG_BIN_HOME"
PATH="$PATH:$DOTFILES_HOME/bin"
export PATH

# Colorized output and alternatives
# check: https://wiki.archlinux.org/index.php/Color_output_in_console 

# load Generic Colouriser (GRC) aliases
# note: Wrappers replace output of commands with escape sequences. Some shell scripts and programs which use the output of standard shell utilities may work wrong.
[ -s "/etc/profile.d/grc.sh" ] && . "/etc/profile.d/grc.sh"

# alias ls='ls --color=auto'
# alias ls='exa --long --git' # exa is close but not fully compliant with ls
alias ls='eza'
alias grep='grep --colour=auto'
alias egrep='egrep --colour=auto'
alias fgrep='fgrep --colour=auto'
alias diff='colordiff'
alias cat='bat'
alias ps='grc ps'
alias ip='ip -c'

# Source config partials
for partial in "$DOTFILES_HOME/shell/partials/"*; do
  # shellcheck source=/dev/null
  . "$partial"
done

# Source private config 
# shellcheck source=/dev/null
[ -f "$DOTFILES_HOME/private/profile" ] && . "$DOTFILES_HOME/private/profile"

# Autostart
# lock file to ensure it's run only once per session 
autostart_lock=/run/user/$(id -u)/autostart.lock
if [ -f "$DOTFILES_HOME/shell/autostart" ] && ! [ -f "$autostart_lock" ]; then
  "$DOTFILES_HOME/shell/autostart"
  touch "$autostart_lock"
fi
