#!/bin/zsh
#
# Preferred apps
export EDITOR="nvim"
export SUDO_EDITOR="nvim -d"
export VISUAL="alacritty -e nvim" # alacritty latency ~0.5s, urxvt is faster
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
#export MANPAGER="nvim -c 'set ft=man ts=8 nomod nolist noma'" # slower than bat
export BROWSER="chromium"

# XDG
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"

# History
export HISTFILE="$XDG_DATA_HOME/shell/history"
export HISTSIZE=10000
export SAVEHIST=10000

# Path
export PATH=/bin:/usr/bin/:/usr/local/bin
export PATH=$PATH:"$HOME/.local/bin"
export PATH=$PATH:"$HOME/Dev/sys/dotfiles/scripts"
export PATH=$PATH:"$HOME/Dev/sys/dotfiles/scripts/private"

# Load Generic Colouriser (GRC) aliases
# note: Wrappers replace output of commands with escape sequences. Some shell scripts and programs which use the output of standard shell utilities may work wrong.
[ -s "/etc/profile.d/grc.sh" ] && source "/etc/profile.d/grc.sh"

# Load user aliases overriding previous aliases
# shellcheck disable=SC1090
[ -f "$XDG_CONFIG_HOME/shell/aliases" ] && source "$XDG_CONFIG_HOME/shell/aliases" 
[ -f "$XDG_CONFIG_HOME/shell/private/aliases" ] && source "$XDG_CONFIG_HOME/shell/private/aliases" 

# Autostart
# lock file ensure it's run only once per session 
autostart_lock=/run/user/$(id -u)/autostart.lock
if [ -f "$XDG_CONFIG_HOME/shell/autostart" ] && ! [ -f "$autostart_lock" ]; then
    "$XDG_CONFIG_HOME/shell/autostart"
    touch "$autostart_lock"
fi

# Source partials
for partial in "$XDG_CONFIG_HOME/shell/config/"*; do
  source "$partial"
done
