#!/bin/bash
# Recipe for Dotfiles Setup.

# X11
_link	"x11/Xresources"                  ".Xresources"

# Shell
_link "shell/aliases"                   ".config/shell/aliases"
_link "shell/autostart"                 ".config/shell/autostart"
_link "shell/config"                    ".config/shell/config"
_link "shell/completions"               ".config/shell/completions"
_link	"shell/profile"                   ".profile"

# Zsh 
_link	"zsh/zshrc"                       ".zshrc"
_link "zsh/zsh"                         ".config/zsh"

# Bash
_link	"bash/bashrc"                     ".bashrc"

# Starship
_link	"starship/starship.toml"          ".config/starship.toml"

# Tmux
_link "tmux"                            ".config/tmux"

# Alacritty
_link "alacritty/alacritty.yml"         ".config/alacritty.yml"

# Kitty
_link "kitty"                           ".config/kitty"

# Vim
_link "vim"                             ".config/vim"

# Git
_link "git/config"                      ".gitconfig"

# Utils
_link "templates"                       ".templates"

# Rofi 
_link "rofi"                            ".config/rofi"

# Weechat
_link "weechat"                         ".config/weechat"

# Gaming
_link "mangohud/MangoHud.conf"          ".config/MangoHud/MangoHud.conf"

# Systemd
_link "systemd/user"                    ".config/systemd/user"
