#!/bin/bash
# Opens URI in a normal or in a private browser session depending on matching of a set of regular expressions.

uri="$1"
browser=firefox
browser_signon=chromium

# open default browser if URI is empty
if [ -z "$1" ]; then
    $browser
fi

# signon_file is a file with regex patterns for URI separated by new line
signon_file="$XDG_CONFIG_HOME/browser/signon" 

mapfile -t signon_patterns <"$signon_file"

for regex in "${signon_patterns[@]}"; do
    echo "${BASH_REMATCH[*]}"
    if [[ $uri =~ $regex  ]]; then
        $browser_signon "$uri" &>/dev/null; exit
    fi
done

$browser "$uri" &>/dev/null; exit

