#!/bin/bash
# Opens URI in a normal or in a private browser session depending on matching of a set of regular expressions.

uri="$1"
browser_default=firefox
browser_signon=chromium

# path to file with regex patterns for URI separated by new line
signon_file="$XDG_CONFIG_HOME/browser/signon"

# open default browser if URI is empty
if [ -z "$1" ]; then
    $browser_default &>/dev/null & exit
fi

# read signon patterns from file
mapfile -t signon_patterns <"$signon_file"

# ignore empty and match URI with each regex 
for regex in "${signon_patterns[@]}"; do
    if [[ -n $regex ]] && [[ $uri =~ $regex ]]; then
        $browser_signon "$uri" &>/dev/null & exit
    fi
done

$browser_default "$uri" &>/dev/null & exit

