#!/bin/bash
# Compress a file or a directory into an encrypted 7z archive.

path="${NAUTILUS_SCRIPT_CURRENT_URI:7}" # extract path from url
path="`python3 -c "import sys, urllib.parse as ul; \
    print(ul.unquote_plus(sys.argv[1]))" $path`/" # decode
files=(${NAUTILUS_SCRIPT_SELECTED_FILE_PATHS//"$path"/}) # extract relative paths

password=`zenity --password` || exit # will exit if cancelled

7z a -t7z -mhe=on -p"$password" `date +%Y-%m-%dT%H-%M-%S`.7z $files
