#!/usr/bin/env bash
# Pull safely from all subdirs containing a Git repo

# usage: git-pull-all <path-to-parent-dir> (optional)

# Change dir to inputted path if valid
if [ -d "$1" ]; then
  cd "$1" || exit
fi

mapfile -t repos < <(\
                     fd -t d --unrestricted '\.git$' \
                     --exclude "**/vim/plugged/" \
                     --exclude "**/zinit/plugins/" \
                     --exclude "**/Trash/" \
                     --exclude ".cache" \
                     --exclude ".emacs.d/" \
                     --exclude ".config/emacs/" \
                     --exclude ".local/share/cargo/" \
                     --exclude ".local/share/docker/" \
                     --exclude ".local/share/go/" \
                    )

for repo in "${repos[@]}"; do
  # trim .git/
  path="${repo%.git/}"

  # run one by one
  # sem -j+0 git-pull-safe "$path"

  # run in parallel
  sem -j 4 git-pull-safe "$path"

  # NOTE: GitHub limit is 4 simultaneous connections
done

# wait for tasks to finish
sem --wait
