#!/bin/bash
#
# Upscale and convert images to an Internet friendly resolution and format

# @author: Daniel Souza <me at posix dot dev dot br>
# @license: GPL3
# @deps: imagemagick, realesrgan-ncnn-vulkan
# @usage:
#     upscale file.[png|jpg|jpeg]

# NOTE: Real-ESRGAN upscaling method only support PNG and JPG

# Defaults
defaultWidth=3840
defaultFormats=(avif jpg)
defaultQuality=90 # lossless
# defaultModel="realesr-animevideov3" # denoise more
defaultModel="realesrgan-x4plus" # denoise less

# Formatting strings
reset="\e[0;0m"
yellow="\e[1;33m"
blue="\e[1;34m"
red="\e[1;31m"
strong="\e[1;39m"

# Dependencies
deps=(convert identify realesrgan-ncnn-vulkan)
for prog in "${deps[@]}"; do
  if [ ! "$(command -v "$prog")" ]; then
    printf "${red}Required dependency not found: ${strong}%s${reset}\n" "$prog"
    exit 1
  fi
done

# Input Path Inference
inputPath="$1"
if [ ! -f "$inputPath" ]; then
  printf "${red}Input file not found: ${strong}%s${reset}\n" "$inputPath"
  exit 1
fi

inputDir="$(dirname "$inputPath")"
inputFile="$(basename "$inputPath")"
inputName="${inputFile%.*}"
# inputExtension="${inputFile##*.}"

# Dimensions Inference
inputInfo=$(identify "$inputPath")
inputWidth=$(perl -pe 's|.*?([0-9]+)x.*|$1|' <<< "$inputInfo")
# inputHeight=$(perl -pe 's|.*x([0-9]+).*|$1|' <<< "$inputInfo")

# if [ "$inputWidth" -eq "$inputHeight" ]; then
#   inputType="squared"
# elif [ "$inputWidth" -gt "$inputHeight" ]; then
#   inputType="landscape"
# else
#   inputType="portrait"
# fi

# Library
_upscale() {
  printf "${blue}Upscaling with ${yellow}%s${reset}\n" "$defaultModel"
  realesrgan-ncnn-vulkan -n "$defaultModel" -i "$1" -o "$2" &>/dev/null 
  # NOTE: realesrgan-ncnn-vulkan isn't working with paths that contain spaces
}

_convert() {
  local _output="${_output}.${_format}"
  printf "${blue}Converting to ${yellow}%s${reset}\n" "${_format^^}"
  
  if [ -f "$_output" ]; then
    printf "${red}Output file already exists: ${strong}%s${reset}\n" "$_output"
    exit 1
  fi
  
  convert -quality ${defaultQuality} -resize ${defaultWidth}x\> "$_input" "$_output" &>/dev/null
}

# Main
_output="${inputDir}/${inputName}"

if [ "$inputWidth" -lt "$defaultWidth" ]; then
  tmpPath="/run/user/$(id -u)/upscale/$inputPath"
  mkdir -p "${tmpPath%/*}" # create dirs for tmpFile
  _upscale "$inputPath" "$tmpPath"
  _input="$tmpPath"
  _output="${_output}_${defaultModel}"

else
  _input="$inputPath"
  _output="${_output}_original"
fi

for _format in "${defaultFormats[@]}"; do
  _convert
done
  
[ -f "$tmpPath" ] && rm "$tmpPath"
