#!/bin/bash
# Link cache files to /run/user/<user_id>

uid=$(id -u) 
cache_dirs=("chromium" "mesa_shader_cache" "mozilla" "thunderbird")
config_dirs=("Code - OSS/Cache" "Code - OSS/CachedData" "Code - OSS/CachedExtensions" "Code - OSS/Code Cache" "Code - OSS/GPUCache" "discord/Cache" "discord/Code Cache" "discord/GPUCache" "Electron" "variety/wallpaper" "whatsapp-nativefier-d40211/Cache" "whatsapp-nativefier-d40211/GPUCache" "whatsapp-nativefier-d40211/blob_storage")
config_files=("variety/history.txt" "variety/variety.log" "variety/.last_change_time")

for dir in "${cache_dirs[@]}"; do
	mkdir -p "/run/user/$uid/cache/$dir" && rm -rf "${XDG_CACHE_HOME:?}/$dir" && ln -s "/run/user/$uid/cache/$dir" "${XDG_CACHE_HOME:?}/$dir"
done

for dir in "${config_dirs[@]}"; do
	mkdir -p "/run/user/$uid/config/$dir" && rm -rf "${XDG_CONFIG_HOME:?}/$dir" && ln -s "/run/user/$uid/config/$dir" "${XDG_CONFIG_HOME:?}/$dir"
done

for file in "${config_files[@]}"; do
	rm -f "${XDG_CONFIG_HOME:?}/$file" && ln -s "/run/user/$uid/config/$file" "${XDG_CONFIG_HOME:?}/$file"
done

