#!/bin/bash
# Compress files

if [ $# -lt 1 ] || [ $# -gt 2 ] ; then
    echo "ERROR: invalid number of arguments, it should be 1 or 2"
    exit 1
fi

if [ $# -eq 1 ]; then
# I am feeling lucky mode
# zst is best compression
# usage: compress <path>
    inPath="$1" # input path
    [ -e "$inPath" ] || exit 1 # fail with file or dir does not exist
    outName="${inPath%.*.*}" # remove extension if any
    outName="${outName%[/]}" # remove trailing slash if any
    tar -cf - "$1" | zstd > "$outName.tar.zst"        

else
# Normal mode
# note: bzip, gzip only compress files and write in place
# and so weren't included
# usage: compress <file> <path>
    # fail if file exists
    outFile="$1" && [ -f "$outFile" ] && exit 1
    # fail if path is not a dir or file
    inPath="$2" && [ -e "$inPath" ] || exit 1
    case "$outFile" in
      *.tar)    tar -cf  "$outFile" "$inPath";;
      *.tar.*)  tar -caf "$outFile" "$inPath";;
      *.zip)    zip      "$outFile" "$inPath";;
      *.7z)     7z a     "$outFile" "$inPath";;
      *) echo "'${outFile#*.}' not supported by compress";;
    esac
fi
