#!/usr/bin/env sh
# Stage all changes, commit with today's date as message and push to remote.
# It's an educated function that do not push when improper and try to make amends.

# usage: git-yolo <path-to-repo> (optional)

# cd to repo if valid path is inputted
if [ -d "$1/.git" ]; then
  cd "$1" || exit
fi

# set commit message
today="$(date '+%y-%m-%d')"
# get last commit message
last_commit="$(git shortlog -1 | sed -n '2p' | sed 's/ //g')"

# add all files
git add -A

# amend if it was already committed today
if [ "$today" = "$last_commit" ]; then
    git commit --amend -m "$today"
else
    git commit -m "$today"
fi

# push if remotes are set
if git ls-remote 2>/dev/null; then
    git push
fi
