#!/usr/bin/env bash 
# Helper for Web Development
# danisztls © 2021 
# MIT License

function printHelp() {
  printf "\n%s\n" "usage: web lorem n"
}

# query CorporateLorem API for paragraphs, extract it and send to clipboard
function getLorem() {
  local paragraphs
  if [ "$1" ]; then
    paragraphs="$1"
  else
    paragraphs="1"
  fi

  curl "https://corporatelorem.kovah.de/api/$paragraphs" |
  sed -E 's/^.*u003e(.*)\\u003c.*$/\1/;s/\\//g' |
  xclip
}

case $1 in
	l|lorem) getLorem "$2";;
  *) printHelp;;
esac
