#!/bin/sh

# pacman + aur
alias p='paru'

# remove orphan packages and free cache 
alias pacman-clean='sudo sh -c "pacman -Qtdq >/dev/null && pacman -Rns $(pacman -Qtdq)"; paccache -rk 1; paccache -ruk 0'

# make
alias makeinfo="makepkg --printsrcinfo > .SRCINFO"
alias makesums="makepkg --geninteg >> PKGBUILD"
