#!/bin/sh
export GEM_HOME="$XDG_DATA_HOME/gem"
export PATH=$PATH:"$GEM_HOME/bin"
export GEM_SPEC_CACHE="$XDG_CACHE_HOME/gem" 
export BUNDLE_PATH="$GEM_HOME/ruby/3.0.0"
export BUNDLE_USER_CONFIG="$XDG_CONFIG_HOME/bundle"
export BUNDLE_USER_CACHE="$XDG_CACHE_HOME/bundle"
export BUNDLE_USER_PLUGIN="$XDG_DATA_HOME/bundle"
