#!/bin/sh

export VIMINIT="set runtimepath^=~/.config/vim|set runtimepath+=~/.config/vim/after|source ~/.config/vim/vimrc" # vim and neovim

alias vim='nvim'
alias vimdiff='nvim -d'
alias vdiff='nvim -d' # vd is for visidata
