#!/bin/sh
# export VIMINIT="set runtimepath^=~/.config/nvim|set runtimepath+=~/.config/nvim/after|source ~/.config/nvim/init.lua"
unset VIMINIT

alias vim='nvim'
alias vimdiff='nvim -d'
alias vdiff='nvim -d'
