" plugins
call plug#begin('$XDG_CONFIG_HOME/vim/plugged')
" search files
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
" browse files 
Plug 'preservim/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'ryanoasis/vim-devicons'
" status line
Plug 'vim-airline/vim-airline'
" git highlight, un/stage changes
Plug 'airblade/vim-gitgutter'
" git workflow
Plug 'jreybert/vimagit'
" syntax highlighting
Plug 'vim-syntastic/syntastic'
" markdown features
Plug 'mzlogin/vim-markdown-toc'
Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app & yarn install' }
" python live editor 
Plug 'metakirby5/codi.vim'
" org mode
Plug 'jceb/vim-orgmode'
call plug#end()

"set vim info path
set viminfo+='1000,n$XDG_CACHE_HOME/vim/viminfo
if has('nvim') | let &viminfo .= '.nvim' | endif

"set nocompatible
filetype plugin indent on
syntax on
set encoding=utf-8

" line number
set number relativenumber
nmap <leader>h :setlocal number! relativenumber!<CR>

" 4 spaces tab
set tabstop=4
set shiftwidth=4
set expandtab

" autocompletion
set wildmode=longest,list,full

" fix splits
set splitbelow splitright
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

" clipboard
vnoremap <C-c> "*y :let @+=@*<CR>
map <C-v> "+P

" spell-check
nmap <leader>en :setlocal spell! spelllang=en_us<CR>
nmap <leader>pt :setlocal spell! spelllang=pt_br<CR>

" vim auto-update
set updatetime=250

" disable automatic commenting on new line
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

" nerdtree
map <leader>b :NERDTreeToggle<CR>
let g:NERDTreeGitStatusUseNerdFonts = 1

" airline
let g:airline#extensions#tabline#enabled = 1
"let g:airline_powerline_fonts = 1

" gitgutter
highlight GitGutterAdd    guifg=#009900 ctermfg=2
highlight GitGutterChange guifg=#bbbb00 ctermfg=3
highlight GitGutterDelete guifg=#ff2222 ctermfg=1

" syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
nmap <leader>s :SyntasticReset
nmap <leader>ss :SyntasticCheck
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" markdown-preview
"let g:mkdp_refresh_slow = 1
let g:mkdp_browser = "electron"
nmap <leader>p <Plug>MarkdownPreviewToggle

" fzf
nmap <leader>f :Files

"vim-markdown
let g:vim_markdown_math = 1
let g:vim_markdown_frontmatter = 1
let g:vim_markdown_folding_disabled = 1
set conceallevel=2

"vim-markdown-toc
let g:vmt_fence_text = 'TOC'
let g:vmt_fence_closing_text = '/TOC'
let g:vmt_list_item_char = '-'
nmap <leader>t :GenTocGitLab<CR>

