# If not running interactively, don't do anything.
[[ $- != *i* ]] && return

# Reload .profile
# changes get in effect in the same session
[ -f "$HOME/.profile" ] && source "$HOME/.profile" 

export TERM="xterm-256color"	# getting proper colors
export HISTCONTROL=ignoredups:erasedups	# no duplicate entries

# enable history appending instead of overwriting
shopt -s histappend

# sigwinch fix
shopt -s checkwinsize

# change the window title of X terminals
case ${TERM} in
	xterm|rxvt*|Eterm*|aterm|alacritty|kterm|gnome*|interix|konsole*)
		PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME%%.*}:${PWD/#$HOME/\~}\007"';;
	screen*) # && exec zsh # use zsh on X terminals
		PROMPT_COMMAND='echo -ne "\033_${USER}@${HOSTNAME%%.*}:${PWD/#$HOME/\~}\033\\"';;
esac

# Starship
eval "$(starship init bash)"

# Direnv
eval "$(direnv hook bash)"
